# Generated by Django 5.2.6 on 2025-09-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
