# Generated by Django 5.2.1 on 2025-05-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_customuser_aadhar_number_customuser_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='previous_diagnoses',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='public_key',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
