# Generated by Django 5.2.1 on 2025-05-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_date_of_birth_patientprofile_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
