# Generated by Django 5.2.6 on 2025-09-07 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('topk', models.IntegerField(default=10)),
                ('results', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
